{% set name = "geoalchemy2" %}
{% set camelName = "GeoAlchemy2" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.tar.gz
  sha256: 8e6b376120245c4813ec3e9c7b8c2eb5d600e52e88f4a638fa12ac42df0c505c

build:
  preserve_egg_dir: True

  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - sqlalchemy >=0.8

  run:
    - python
    - setuptools
    - sqlalchemy >=0.8

test:
  imports:
    - geoalchemy2

about:
  home: http://geoalchemy.org/
  license: MIT License
  summary: 'Using SQLAlchemy with Spatial Databases'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
