{% set name = "GeoAlchemy2" %}
{% set version = "0.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "7d66d01af82d22bc37d3ebb1e73713b87ac5e116b3bc82ea4ec0584bbaa89f89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  preserve_egg_dir: True
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - sqlalchemy >=0.8

test:
  imports:
    - geoalchemy2

about:
  home: http://geoalchemy.org/
  license: MIT
  license_family: MIT
  license_file: COPYING.rst
  summary: 'Using SQLAlchemy with Spatial Databases'
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2
  
extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
