{% set name = "GeoAlchemy2" %}
{% set version = "0.18.0" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "9a04690cc33fbc580d15c7c028d9b1b1ea08271489730096c7092e1d486c2b7a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/G/GeoAlchemy2/geoalchemy2-0.18.0.tar.gz
  sha256: {{ hash_val }}

build:
  preserve_egg_dir: true
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=42
    - setuptools_scm
    - wheel
    - setuptools-scm >=3.4
  run:
    - python
    - setuptools
    - sqlalchemy >=1.4
    - packaging
  run_constrained:
    - Shapely >=1.7

test:
  imports:
    - geoalchemy2
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://geoalchemy.org/
  license: MIT
  license_family: MIT
  license_file: COPYING.rst
  summary: Using SQLAlchemy with Spatial Databases
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
