{% set name = "GeoAlchemy2" %}
{% set version = "0.4.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "d9810b2413ca5e61e1b50997eeaa5468bf79bfd829f46ccad8ff6e5648deb1c7" %}
{% set build_num = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  preserve_egg_dir: True
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - sqlalchemy >=0.8

test:
  imports:
    - geoalchemy2

about:
  home: http://geoalchemy.org/
  license: MIT
  license_family: MIT
  # license_file: No manifest - see https://github.com/geoalchemy/geoalchemy2/pull/147
  summary: 'Using SQLAlchemy with Spatial Databases'
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2
  
extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
