{% set name = "GeoAlchemy2" %}
{% set version = "0.9.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "de0d0b1ff2f7f26ddff0a69d9a33940020707caedd442fa13b28affec842dafb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  preserve_egg_dir: True
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - wheel

  run:
    - python
    - setuptools
    - sqlalchemy >=1.1

test:
  imports:
    - geoalchemy2
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://geoalchemy.org/
  license: MIT
  license_family: MIT
  license_file: COPYING.rst
  summary: 'Using SQLAlchemy with Spatial Databases'
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2
  
extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
