# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bPyx0kgVBx6cY3TDRaKyyTTY0r8uTPNtgmLSPY+hf9JeAmz5caH8RaZoxrf2TF8dGaFH6eaRm3gDxrvtS3H66qDI5eNNpE1L7kJELhXDKEk8Va22MTQCwy2CoUocnx0FhKv/JtxQEL1TCf1yAu9clKqhksoICVqCNQMjGr6oHRLwXPDcA/xYDEr8p+GYpBl3pEzzR6VHZadFCTzZMhjcLX4A0v7dMzoNNshRvHVSU6uQpAjiWwXWbrYbVT4L9ZFWk7/Bl9wLYSoAVLFB8RQyrReAkgfVNnfKkd8DKwpGGpytRUxdcs4CgunMEA0OHcIiza63Ww4gvhSSznUpq4ieU3VZeeBvCQk9MyUZNGFnBCm3XaO/i5SJnhJpLQJ1KfXmc5BIk/nJqUm3/EXUgKtT4VzORJWfH75UhAyieLVsfbQuPlh8XV0xohnDhyf+v7xXsL9A0vFz+4+oFNSvJs2LrOzAENU4xnTFWcQQ+NXBzOjt5fD7QyQ/OVBij6fDSSvOgmWWRq8FrLvwm+6NTahdBb65pAUciT3JNJg6/Zn/VAdkHWoz1CewuIU89MSbiCt9qCmpCb4rKcV3V4G5wvKll27jvQkhAqHB7prpk2WKlJtsBHu0zKg0CPJ8VP3CkRhO0fFpdYd1ZbUUi4aAStXMdgDNPOG61rUnAXl8bXhK3Ms="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
