travis:
  secure:
    BINSTAR_TOKEN: AZxtG/Kz7d/WEZ375d2GUVmmaYh3WcJI5hEv1Vv/dau7L1qJSIFD6+X0Y/C++btc7gnh+r5qdapKBfLte0QgsBgy19AlewT5XIWtsgZVSvqb7TRsPKR2us3ndR1YtDMtt6QDeCVUWqLfMYQoXYJ2Kc4isCb0HA74HJTEWIon798kGEUxiFBmz/GgwJW0Qlp5mnViaM+KldBlcFczAT68MHQtlWe2H70A+SS7TibKjBptrJhznecPklvzUUb+UkMvyr2q1xfNmVffVGFBIN04xE/84rmqSLvL8zYElTbcbmq8nqKYKusIaxwpZdafuiHUuWaiPJu7doBVyTUrchJxGx6EDNMogWMDWDdX3f46G/sNQLFk0UwowoQY5p/Grb8ivN1JlZIjr9ih1oKHjoPQ6AleW3vZxyXQO7VK/wTxgKTW2Skja3CUbs3UayZvkFi4fRb0Mmv1zNC9+l/dphfPvO77PdIX1fBk6RufAD9uBa31ecFm5qodJI/RnMpmlG5mSzy95cJ31hv/j7A6IO+fs2nkDCrYUU70DD1qWURMNQhyKBxrAm6bclyNGnOxI8OWp/c0pkqO+XNvrpYBSGTT5MWYHmQPR9VRp+hYcpXPZmlG3WddO8wyqEOpUDssVlLVGfr5FOToGr4GreUxw4GLUOpAhIauCVdu4ZVuRTw++hk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
