travis:
  secure:
    BINSTAR_TOKEN: YHdvJrtUF1nLfI+DDDK5bgJPkYbnbkuaVP7UmPqt2791aZHA4wHUxLwVk8f1IBoapM3ZmyTeBvlH2b08NjtiI3U+1OIdITZgDupm0pvX+YWCP0BvIDWgZt6yTMt0PWuM5ErH3exLswdNi5T9flHTddsW0GGblkNXYVSfS5CKKZoeRIbx9CKlqg88csmQnqe9OeN2f+R5wQXzLCJdc9WujHAXi78sY6XcHDWkdGGDFUqS6pOS4n7CJ6F8Wm6+5wI+ySDscrBiIQI32E/LIr1xJtcoBE2LwFfrD4+6bBCHFSSwT+4+1FjmYE8P4uNd3/uGYOtnsg9bmiNkW0kUzcfXPVO79Jl2sZ0GfDtKXuClecL92NEDVW8dYLNbb9h4BaaB2XsHwyWmFNQxvjPe+YN+ZJgSqyQDIknzQEDGHsmfL84uqYr48sHrgypekH+ny1m2zGw/P7fs8P0/XIQ72Is7RYv12sId7OTFnxJmuAdDbF7SIDmS905vuLuieOEWcO4a3fXbMZ9A66IyK9qTODHiMqesOkpHHaQ1r5DPO/8YZOTi+UJiSwdZh6vjkPv9Bs3f7OMTuDS1cFEnbGtiPlz0zjxaZz67WBGLsVPRwfxcgzmm3YZ3btfRwirPrJkwgDDU2WhI+cwspegHIPdsNnVzzrX62LE4mka6aGvQCkRL7Gw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
